### ISSUE TITLE
not true lazy loading

### ISSUE THREAD

**Issue by ncrawlins** [aayaresko/angular2-live-chat-and-tasks-crud#1]
all of your "lazy loaded" modules are being imported in your app module, so there is no lazy loading going on.

**Comment by aayaresko** [comment]
hi! are you sure about that?

**Comment by aayaresko** [comment]
oh! I got it! Thnx for the tip, I've totally forgot to remove them from app import. Nice to know that someone is actually reading the code! Thnx again!
